### ISSUE TITLE
List expression problem

### ISSUE THREAD

**Issue by Mayonnaisu** [Blackdeer1524/CambridgeDict.py#1]
"List expression not allowed in type annotation" is what it said when I ran your code. Could you please fix it? I tried to tinker with it on my own and end up getting even more errors. Clearly I didn't know what I was doing.

**Comment by Mayonnaisu** [comment]
I just ran it on Python IDLE instead of VS Code and it works. I don't know why though. Anyway, thanks for creating this!

**Comment by Blackdeer1524** [comment]
Hi! Just updated type hints so these warnings should disappear. Also fixed return type of `defne` function

**Comment by Mayonnaisu** [comment]
Hi, thanks a lot!
