### ISSUE TITLE
Some information is missing

### ISSUE THREAD

**Issue by Mayonnaisu** [Blackdeer1524/CambridgeDict.py#2]
Hello, I realized that there are some pieces of information that are not get extracted. For example, if we search for "more", it only returns "predeterminer" as the category even though there should be four categories (determiner, pronoun, adverb, and adjective), and it also misses some of its phonetic transcriptions. Furthermore, it also misses one definition out of four. I hope that it will be fixed.

**Comment by Blackdeer1524** [comment]
Hi. Just fixed missing POS problem. But other then that, scrapper still works. Please send more informations so that I could replicate your problem.

**Comment by WongUrip** [comment]
Ok, I am going to elaborate the previous example. I just checked the latest version, and it still missing one POS (adjective) when searching for "more". Maybe that's also why it misses two definitions:
1.  a larger or extra number or amount (of); comparative ofmany or much
2. More is used to form the comparative of many adjectives and adverbs

and two IPAs or more exactly one:
1.  /mɔr, moʊr/

All of the missing information for this particular example is at the two last rows of all information.

**Comment by Mayonnaisu** [comment]
Ok, I am going to elaborate the previous example. I just checked the latest version, and it is still missing one POS (adjective) when searching for "more". Maybe that's also why it misses two definitions:

1. a larger or extra number or amount (of); comparative ofmany or much
2. More is used to form the comparative of many adjectives and adverbs

and two IPAs or more exactly one:
1. /mɔr, moʊr/

All of the missing information for this particular example is at the two last rows of all information on the webpage.

**Comment by Mayonnaisu** [comment]
Another example, the word "is" has only one definition when there should be two.
Missing:
1. be, used with he/she/it

The POS is returned as "idiom" even though there is the normal one.
Missing:
1. verb

There are only two IPAs when there should be seven.
Missing:
1. US: weak /z/ /s/
2. UK: weak /z/ /s/
3. US: /ɪz, əz/

**Comment by Blackdeer1524** [comment]
> Ok, I am going to elaborate the previous example. I just checked the latest version, and it is still missing one POS (adjective) when searching for "more". Maybe that's also why it misses two definitions:
> 
>     1. a larger or extra number or amount (of); comparative ofmany or much
> 
>     2. More is used to form the comparative of many adjectives and adverbs
> 
> 
> and two IPAs or more exactly one:
> 
>     1. /mɔr, moʊr/
> 
> 
> All of the missing information for this particular example is at the two last rows of all information on the webpage.

You see, scrapper views this last section as a separate "dictionary" - American one. There is even "American Dictionary" in the header. There are 3 dictionaries in total: English (default), American, and Business ones. Scrapper parses only one dict at a time. So if you need to scrape American version, you have to pass `dictionary_index` parameter to `define`.

**Comment by Blackdeer1524** [comment]
> Another example, the word "is" has only one definition when there should be two. Missing:
> 
>     1. be, used with he/she/it
> 
> 
> The POS is returned as "idiom" even though there is the normal one. Missing:
> 
>     1. verb
> 
> 
> There are only two IPAs when there should be seven. Missing:
> 
>     1. US: weak /z/ /s/
> 
>     2. UK: weak /z/ /s/
> 
>     3. US: /ɪz, əz/

Fixed. I also changed resulting scheme a little, so check out README first. And thanks for your bug reports, I really appreciate it.

**Comment by Mayonnaisu** [comment]
> > Ok, I am going to elaborate the previous example. I just checked the latest version, and it is still missing one POS (adjective) when searching for "more". Maybe that's also why it misses two definitions:
> > ```
> > 1. a larger or extra number or amount (of); comparative ofmany or much
> > 
> > 2. More is used to form the comparative of many adjectives and adverbs
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and two IPAs or more exactly one:
> > ```
> > 1. /mɔr, moʊr/
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > All of the missing information for this particular example is at the two last rows of all information on the webpage.
> 
> You see, scrapper views this last section as a separate "dictionary" - American one. There is even "American Dictionary" in the header. There are 3 dictionaries in total: English (default), American, and Business ones. Scrapper parses only one dict at a time. So if you need to scrape American version, you have to pass `dictionary_index` parameter to `define`.

Ah, I see. So that's how it is.

**Comment by Mayonnaisu** [comment]
> > Another example, the word "is" has only one definition when there should be two. Missing:
> > ```
> > 1. be, used with he/she/it
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The POS is returned as "idiom" even though there is the normal one. Missing:
> > ```
> > 1. verb
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > There are only two IPAs when there should be seven. Missing:
> > ```
> > 1. US: weak /z/ /s/
> > 
> > 2. UK: weak /z/ /s/
> > 
> > 3. US: /ɪz, əz/
> > ```
> 
> Fixed. I also changed resulting scheme a little, so check out README first. And thanks for your bug reports, I really appreciate it.

Ok, will do. You're welcome. Me too.
