### ISSUE TITLE
script miss parsing some of the existing words

### ISSUE THREAD

**Issue by fastcd** [Blackdeer1524/CambridgeDict.py#3]
In some languages there is empty results {}, for example:

```
if __name__ == "__main__":
    from pprint import pprint

    pprint(define(word="endowing",

                  bilingual_vairation="polish"))
```

And if we are going to cambridge site. it exist!
dictionary.cambridge.org/us/dictionary/english-polish/endow

Can you please check? Same situation with ukranian words..

**Comment by Blackdeer1524** [comment]
Ok, will look into this when i will have time.

**Comment by Blackdeer1524** [comment]
Fixed. But if there is still any bugs please let me know
